version: '3'

services:
  web:
    container_name: ${APP_NAME}_web
    build: .
    entrypoint: ./docker/local/api/run.sh
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    ports:
      -   7777:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
  database:
    container_name: ${APP_NAME}_db
    image: mysql:5.7.19
    restart: always
    ports:
      - "33065:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=db
